# Generated by Django 3.2.7 on 2021-09-29 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapi', '0002_poll_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 13, 13, 11, 446372, tzinfo=utc), verbose_name='date published'),
        ),
    ]
